name: "Publish coverage from test suite as comment"
description: "Parse the coverage file from pytest suite, parse and format it to
  be displayed in the PR as a comment."
author: "Loïc Diridollou"

branding:
  icon: "heart"
  color: "red"

# Define your inputs here.
inputs:
  milliseconds:
    description: "Your input description here"
    required: true
    default: "1000"

runs:
  using: node20
  main: dist/index.js
