name: "Publish coverage from test suite as comment"
description: "Parse the coverage file from pytest suite, parse and format it to
  be displayed in the PR as a comment."
author: "Loïc Diridollou"

branding:
  icon: "aperture"
  color: "green"

inputs:
  path:
    description: "Path of the coverage file"
    required: false
  github_ref:
    description: "Reference of the event to find PR number"
    required: false
  project_name:
    description: "Name of the project to filter files"
    required: false
  github_url:
    description: "API URL of the repo"
    required: false
  head_sha:
    description: "Base SHA"
    required: false
  base_sha:
    description: "Head SHA"
    required: false

runs:
  using: node20
  main: dist/index.js
